"""Render complete native instruction templates from one common source."""
from pathlib import Path
import argparse

BANNER = "<!-- Generated by scripts/install/render_guidance.py; edit templates/instructions/. -->\n\n"


def render(root):
    base = root / "templates" / "instructions"
    common = (base / "common.md").read_text(encoding="utf-8").strip()
    codex = (base / "codex.md").read_text(encoding="utf-8").strip()
    # Keep Git Workflow after Subagents: Eval replaces that bounded section.
    before_git, marker, git = common.partition("# Git Workflow\n")
    if not marker:
        raise ValueError("common guidance must contain Git Workflow")
    codex_template = before_git.rstrip() + "\n\n" + codex + "\n\n" + marker + git
    return {"AGENTS.md": BANNER + codex_template + "\n",
            "CLAUDE.md": BANNER + common + "\n"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="read-only generated-file check")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    mismatches = []
    for name, contents in render(root).items():
        path = root / "templates" / name
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != contents:
                mismatches.append(name)
        else:
            path.write_text(contents, encoding="utf-8")
    if mismatches:
        parser.exit(1, "guidance: stale generated templates: " + ", ".join(mismatches) + "\n")
    print("guidance: generated templates are consistent")


if __name__ == "__main__":
    main()
